---
title: "Visualizing Carbon Dioxide Levels Project"
output: html_notebook
---

```{r message=FALSE, warning=FALSE, error=TRUE}
# load libraries and data
library(readr)
library(dplyr)
library(ggplot2)
```

```{r error=TRUE}
options(scipen=10000) #removes scientific notation

#Create NOAA Visualization here:
noaa_data <- read_csv("carbon_dioxide_levels.csv")  # read the data
head(noaa_data)  # observe the data
names(noaa_data)  # observe the column names
str(noaa_data)  # lets us know about the type 

# plot 

noaa_viz <- ggplot(data=noaa_data, aes(x=Age_yrBP, y=CO2_ppmv)) + 
geom_line() +
labs(title="Carbon Dioxide Levels From 8,000 to 136 Years BP", subtitle="From World Data Center for Paleoclimatology and NOAA Paleoclimatology Program", x="Years Before Today (0=1950)", y="Carbon Dioxide Level (Parts Per Million)") +
scale_x_reverse(lim=c(800000,0))
noaa_viz
```

```{r message=FALSE, error=TRUE}
#Create IAC Visualization

 iac_data <- read_csv("yearly_co2.csv")  # read the data
 head(iac_data)
 names(iac_data)
 str(iac_data)

millennia_max <- max(noaa_data$CO2_ppmv)  # find the max of CO2_ppmv in noaa_data set
millennia_max  # prints off the max

# plot

iac_viz <- ggplot(data=iac_data, 
aes(x=year, y=data_mean_global))
iac_viz + 
geom_line() +
labs(title="Carbon Dioxide Levels over Time", subtitle="From Institute for Atmospheric and Climate Science (IAC).", x="Year", y="Carbon Dioxide Level (Parts Per Million)") + geom_hline(aes(yintercept=millennia_max, 
linetype="Some string"))
 
```
